#!/bin/sh

# result=$(cabal list-bin exe:mptcpanalyzer)
# if [ $? -eq 0 ]; then
#   export PATH="$(dirname $result):$PATH"
# fi

MPTCP_PM_EXE=$(cabal list-bin exe:mptcp-pm)
function buildNrun() {
	cabal build -v mptcp-pm
	if [ $? -eq 0 ]; then
    # with our changes sudo should not be necessaery anymore
    cabal run mptcp-pm -- $@
		# ./daemon daemon $@
	fi
}

function rundaemon() {
	cabal build
	sudo setcap cap_net_admin+ep "$MPTCP_PM_EXE"
	cabal run mptcp-pm -- $@
}
